version: '3.8'
services:
  telegraf:
    image: telegraf:1.33.2
    container_name: telegraf
    ports:
      - "8080:8080"
      - "8186:8186"
    restart: unless-stopped
    volumes:
      - "${PWD}:/etc/telegraf"
    command: --config /etc/telegraf/telegraf.conf
